### ISSUE TITLE
create `listProjects.subscribe()`-like API for apps to react on project creation

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-sdk#1]
@samuel.stroschein said in [SHERL-3](https://linear.app/opral/issue/SHERL-3/ide-extension-doesnt-react-when-new-project-is-created#comment-681b7ae8):

> @felixhaeberle you want `listProjects.subscribe()`?

**Comment by NilsJacobsen** [comment]
I feel like all apps might want that. @niklas.buchfink, what do you think?
