### ISSUE TITLE
Figure out how to best configure Lint Rules

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-message-sdk#102]
### Context

Lint rules need a lot of configuration

* Warn or Error
* Filtering
  * Should Apply to MessageBundle
  * Should Apply to Message (including in language that may be missing)
  * Should Apply to Variant (including variant that may be missing)

## Open Questions

* Where is the Severity configuration stored
* How is the Severity configuration surfaced to the user
* Is this Severity exposed to the lint rules

**Comment by LorisSigrist** [comment]
After looking at how ESLint handles lint rule configuration:<br>ESLint uses a combination of pre, and post-filtering for their lint-reports.

* If an entire file is ignored it is not passed to the lint rules 
* Else, all lint rules are executed on the file & ESLint filters out the issues that are relevant afterwards. 

> Lint rule severity (warn/error) and filter rules are not exposed to the lint-rule. They're purely in ESLint's own config

Visually:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/812c3eea-02e8-48d8-ab92-c399f189cdbd/65c3a745-4c40-4146-a3b5-72a163ef1f90?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC84MTJjM2VlYS0wMmU4LTQ4ZDgtYWI5Mi1jMzk5ZjE4OWNkYmQvNjVjM2E3NDUtNGM0MC00MTQ2LWEzYjUtNzJhMTYzZWYxZjkwIiwiaWF0IjoxNzE4ODg4NjU5LCJleHAiOjMzMjg5NDQ4NjU5fQ.vF4uon1aRSNc48hCyHEbrTw1-A1H-fC3FFkf0l-L2Ec " alt="IMG_1034.jpg" width="3859" height="926" />

As for fixing: Rules return callbacks for fixing the issue as part of the message-report. 

```
context.report({
    node: node, // the AST node where the issue is
    message: "Missing semicolon", // the error-message
    fix(fixer) { //callback to fix it
        return fixer.insertTextAfter(node, ";");
    }
});
```

IMO this is suboptimal since the callback cannot be passed between worker boundaries, so having the lint process in a separate worker will be inconvenient. We should consider having the fix be a separate function that get's passed the report.

```
fix(report, fixer) {
  return fixer.insertTextAfter(report.node, ";");
}
```

**Comment by samuelstroschein** [comment]
fix for report seems to make most sense 👍 

* one lint rule can report "different" fixes based on the problem on hand 

regarding severity: 

* severity of lint rules should be stored in settings. 
  * having error and warning hardcoded will eventually fall short because ppl will want their own levels 
* i bet that people want to change the severity of individual messages from things like "error" to "ah no, this is OK mark it as warning to be dealt with it later"

**Comment by samuelstroschein** [comment]
cancelled in favor of lix validation rules [lix validation rules](https://linear.app/opral/project/lix-validation-rules-bdf46c532aa1)
