### ISSUE TITLE
new plugin api

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-message-sdk#119]
### Context

@felix.haeberle asked me if i can take a look at the plugin resolution stuff. 

### Suggestions

1. Change ID to key [MESDK-158](https://linear.app/opral/issue/MESDK-158/minor-rename-pluginid-to-pluginkey) 
2. Remove the need for `plugin.namespace.key` by just doing `key: string`. keep things simple. 
3. remove display name and description (those will likely come from a registry, or … we just link to the product page.)
4. Remove detected language tags because deprecated 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/d74e5e42-ca12-4221-82c5-76c42885bea2/65d9a5b4-0171-4a77-a1b1-9e67d9fbb41a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9kNzRlNWU0Mi1jYTEyLTQyMjEtODJjNS03NmM0Mjg4NWJlYTIvNjVkOWE1YjQtMDE3MS00YTc3LWExYjEtOWU2N2Q5ZmJiNDFhIiwiaWF0IjoxNzIyMzExMDA1LCJleHAiOjMzMjkyODcxMDA1fQ.HgWBhMAs4bNIbBZVx5sNILBkg4azdRo5ZZQ1dr6H9Cg " alt="CleanShot 2024-07-29 at 23.31.27@2x.png" width="2614" height="1746" />

5. Remove plugin resolution except for importing a plugin and validating the settings. <br><br>We don't need to merge APIs anymore. Hence, remove the complexity of plugin resolution aka merging stuff
6. Remove `InstalledPlugins` stuff. <br><br>It's overkill. I would expose the imported plugins as array as a first step and then take it from there. 

```
// let apps handle whatever they need to do 
// by exposing the (sucessfully) imported plugins

const plugin = project.plugins.find((plugin) => plugin.key === "i18next")
await plugin.exportFiles()

const sherlockPlugins = project.plugins.filter((plugin) => plugin.customApi['sherlock'])
```

**Comment by NilsJacobsen** [comment]
Is there still a way to distinguish a plugin from an app or a guide besides checking the id? Because you removed that information? We use that on inlang.com (registry/rendering of product pages/ …)

**Comment by felixhaeberle** [comment]
@samuel.stroschein I do see various issues with parts of this approach.

* without InstalledPlugins, how should an app know that there is a "i18next" plugin? You used this information in the snippet which is supposed to run in Sherlock
* how do I know that an imported plugin ist "imported successfully"? we do not depend on plugins any longer so we would need to dry run roundtrip every function to guarantee its working 
* loosening the plugin name structure: as Nils pointed out, this will lead to inconsistency & also overhead for the current website setup. it has worked great so far, why change a running system if it works? we have enough work elsewhere.

**Comment by samuelstroschein** [comment]
> * without InstalledPlugins, how should an app know that there is a "i18next" plugin? You used this information in the snippet which is supposed to run in Sherlock

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/bc9a3f6f-d4c1-4368-a367-e2fb2e4a23d6/1bd90b23-0d71-4bb7-831a-3f57527f64e8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iYzlhM2Y2Zi1kNGMxLTQzNjgtYTM2Ny1lMmZiMmU0YTIzZDYvMWJkOTBiMjMtMGQ3MS00YmI3LTgzMWEtM2Y1NzUyN2Y2NGU4IiwiaWF0IjoxNzIyMzQ1NzkyLCJleHAiOjMzMjkyOTA1NzkyfQ.RZlHOsih1l7jchuGPJqPhZE3zBi9LKBRmpf8MW8_Jus " alt="CleanShot 2024-07-30 at 09.20.44@2x.png" width="1390" height="450" />

> * how do I know that an imported plugin ist "imported successfully"?

if it exists in the plugin array. else you find an error in project.errors

> * loosening the plugin name structure: as Nils pointed out, this will lead to inconsistency

it doesn't work. 

* the dots break urls and path names, transforming is required
* complex union type for settings
* the website uses registry ids, not keys from plugins

> @nils.jacobsen Is there still a way to distinguish a plugin from an app or a guide besides checking the id?

yes, you know it's a plugin. the marketplace manifest could even have a prop "type" plugin

**Comment by samuelstroschein** [comment]
done as part of the sdk v2 release

**Comment by samuelstroschein** [comment]
massively simplifies all resolution logic
