### ISSUE TITLE
"Invalid host defined options" sherlock error after manually creating settings.json

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#2]
[https://discord.com/channels/897438559458430986/1218873582726156338](https://discord.com/channels/897438559458430986/1218873582726156338)

[https://github.com/mishodzuliashvili/one-punch-man](https://github.com/mishodzuliashvili/one-punch-man)

### to reproduce

```sh
git clone https://github.com/mishodzuliashvili/one-punch-man.git
cd one-punch-man
rm project.inlang/project_id
code .
```

**Comment by jldec** [comment]
![Screenshot 2024-03-17 at 15 12 29](https://github.com/opral/inlang-message-sdk/assets/849592/3cd63e93-619b-42f0-89b1-edf7d6ef5fba)

**Comment by jldec** [comment]
note - @felixhaeberle this problem does not reproduce using a debug CLI or an installed (2.13.0) inlang CLI, or with sherlock running in the debugger. I'm not sure how to isolate the root cause with this constraint. Any ideas?

**Comment by felixhaeberle** [comment]
@jldec tested in a codespace – can't reproduce either.

My reproduction steps:

1. Open codespace.
2. Install Sherlock (verified working)
3. Delete `project_id`
4. Restart Codespace
5. See new `project_id` created
6. Verified Sherlock working

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/97d9f0ab-7b3c-43f8-8f43-e62fbb4fa6f6/8dab8d3c-153b-44a3-a7bb-bc03b711771e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC85N2Q5ZjBhYi03YjNjLTQzZjgtOGY0My1lNjJmYmI0ZmE2ZjYvOGRhYjhkM2MtMTUzYi00NGEzLWE3YmItYmMwM2I3MTE3NzFlIiwiaWF0IjoxNzEwNzE0MzI5LCJleHAiOjMzMjgxMjc0MzI5fQ.dNR7XKOtCjdSmbYcMmc2VvVwR55fB8awrPtPZjtU_t4 " alt="Bildschirmfoto 2024-03-17 um 23.22.05.png" width="1720" height="963" />

**Comment by jldec** [comment]
@felixhaeberle 
Would you mind testing with https://github.com/jldec/jldec-repro.git on your local machine
The repo is empty except for a minimal project.inlang/settings.json

```json
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "en",
  "languageTags": ["en", "ka"],
  "modules": []
}
```

for some reason this still fails for me in the loadProject in sherlock - but i don't know how to debug or instrument the production build of sherlock. 

```
git clone https://github.com/jldec/jldec-repro
cd jldec-repro
rm -f project.inlang/project_id
code .
```

![Screenshot 2024-03-17 at 20 16 45](https://github.com/opral/inlang-message-sdk/assets/849592/76afb97d-bce5-4872-8f9b-82dee4d1c8ed)

**Comment by felixhaeberle** [comment]
But how should the project be loaded? You did not provide a module – or was this intentional?

**Comment by felixhaeberle** [comment]
Got it, will investigate!

**Comment by felixhaeberle** [comment]
@jldec I got this error by loading up the project you provided.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/2f273acf-b3f4-4f6d-8ac2-013003b019ac/352750cf-440f-48b7-95a1-f6385a1939f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8yZjI3M2FjZi1iM2Y0LTRmNmQtOGFjMi0wMTMwMDNiMDE5YWMvMzUyNzUwY2YtNDQwZi00OGI3LTk1YTEtZjYzODVhMTkzOWY2IiwiaWF0IjoxNzExNTU3OTgzLCJleHAiOjMzMjgyMTE3OTgzfQ.b5TiW2r8cdCBjkdTMQTvmsaQAOTFv3BnVXm6D8d6vFg " alt="Bildschirmfoto 2024-03-27 um 17.06.10.png" width="466" height="189" />


With modules defined, I ge this error:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/d85c84f2-6ee9-49a7-99ec-7d50da8ed899/b7ef731b-3758-401f-b8ac-0eadf5282832?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9kODVjODRmMi02ZWU5LTQ5YTctOTllYy03ZDUwZGE4ZWQ4OTkvYjdlZjczMWItMzc1OC00MDFmLWI4YWMtMGVhZGY1MjgyODMyIiwiaWF0IjoxNzExNTU3OTgzLCJleHAiOjMzMjgyMTE3OTgzfQ.X73lvAgU8r2chphukqJz_fE4H7gnJgbRlkTGCu-kphQ " alt="Bildschirmfoto 2024-03-27 um 17.32.10.png" width="472" height="179" />


I'm now into the weeds of creating a production build with logs and seeing where things do not work.

**Comment by jldec** [comment]
@felix.haeberle thanks
I looked a the loadProject() code a bit more and I'm pretty sure there's a race condition which only shows up in the ide-extension and then, not in the debugger. I can do more experiments today, but it would help to be able to run a production build of the extension built locally from source (not installed from the marketplace). Do you know how to do this?

**Comment by felixhaeberle** [comment]
I'll record you a loom on how to approach this: 

* Create production build
* Install it in VS Code
* Look for logs and debug

I'm now recording the Loom.

**Comment by felixhaeberle** [comment]
@jldec [https://www.loom.com/share/05970189947640c0be4019a9f025c4ff](https://www.loom.com/share/05970189947640c0be4019a9f025c4ff)

**Comment by jldec** [comment]
Root cause of this bug was a missing `await` \[here\]([https://github.com/opral/monorepo/blob/26a42043c3c67b393331d10833adcb152b7e9800/inlang/source-code/sdk/src/migrations/maybeCreateFirstProjectId.ts#L44](https://github.com/opral/monorepo/blob/26a42043c3c67b393331d10833adcb152b7e9800/inlang/source-code/sdk/src/migrations/maybeCreateFirstProjectId.ts#L44))
