### ISSUE TITLE
remove `tryCatch` stuff from inlang message sdk

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-message-sdk#27]
### Proposal 

Remove the `tryCatch` stuff from message SDK in favor of standard JS. 

### Value of tryCatch is close to 0 

@samuel.stroschein said in [LIX-59](https://linear.app/opral/issue/LIX-59/cleanup-error-handling-in-lix-and-inlang-message-sdk#comment-07c268d1):

> EDIT: never mind. the value of `tryCatch` is close to 0. 
>
> @jldec what is your issue with the utility function `tryCatch()`? The function doesn't impact API design.
>
> ```
> const file = await tryCatch(() => repo.fs.readFile())
> 
> if (file.error){
>   // do something
> }
> 
> const parsed = tryCatch(() => JSON.parse(file.value))
> 
> if (parsed.error){
>   // do something
> }
> 
> ```
>
> ```
> try {
> 
>   const file = await repo.fs.readFile()
>   const parsed = JSON.parse(file)
> 
> } catch (e){
>   if (e instanceof FileError){
>     //
>   } else if (e instanceof JSONError){
>     //
>   }
> }
> ```

**Comment by samuelstroschein** [comment]
if you remove it, can you check if `tryCatch` is used somewhere else in the monorepo? If not, i vote to remove the function from @inlang/result

**Comment by jldec** [comment]
used in 3 files in the manage package.

**Comment by samuelstroschein** [comment]
@jldec remove in manage package too and then remove the function alltogether?

**Comment by jldec** [comment]
sounds good - ref: INWEB-55

**Comment by samuelstroschein** [comment]
[INWEB-55](https://linear.app/opral/issue/INWEB-55/update-or-deprecate-manageinlangcom)  :)

**Comment by samuelstroschein** [comment]
resolved in sdk v2
