### ISSUE TITLE
Requirements for gender and plurals

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#40]
### Context

Users are asking for inlang to support messages with variant for gender and plurals.

### Proposal

Introduce new types which are aligned with ICU Message Format 2 messages and a new message bundle type to collect messages translated for different locales.

**Comment by W1M0R** [comment]
This format for pluralization seems to be very flexible, in case this matches your goals: https://github.com/nicksnyder/go-i18n/blob/b42d9bd0c568eebf5ce123ec94b9b13438f46855/i18n/bundle_test.go#L101

![image](https://github.com/opral/inlang-message-sdk/assets/618853/23f15013-7a06-48a4-a02d-09185ca98a5f)

**Comment by pichfl** [comment]
How about https://github.com/unicode-org/message-format-wg/blob/main/spec/formatting.md which is the formal spec for the ICU Message and is also implemented in Format.JS https://formatjs.io/docs/core-concepts/icu-syntax/#plural-format

**Comment by LorisSigrist** [comment]
@pichfl Good Shout! The ICU MessageFormat 2.0 is actually what we're focussing our internal efforts on

**Comment by pichfl** [comment]
Much appreciated! I'm involved in a few larger projects in desperate need of this, so if there is anything else I can do to move things along, I'd be happy to help.
