### ISSUE TITLE
Report loading-errors from Plugins

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-message-sdk#42]
Currently if a loading-error happens in a Plugin during message loading, perhaps due to a syntax error, it's quietly ignored. We should add a way to report loading issues from plugins so we can inform developers why loading is not working

**Comment by jldec** [comment]
Followed up to ask for failing json. The description was a bit unclear about where exactly the error was not being trapped. [https://discord.com/channels/897438559458430986/1233725855763660891/1234449997487935528](https://discord.com/channels/897438559458430986/1233725855763660891/1234449997487935528)

**Comment by jldec** [comment]
en.json and sv.json

```
{
    "$schema": "https://inlang.com/schema/inlang-message-format",
    "dashboard": "Dashboard",
}

{
    "$schema": "https://inlang.com/schema/inlang-message-format",
    "dashboard": "Översikt",
}
```
