### ISSUE TITLE
get rid of versioned interface packages

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-message-sdk#46]
### Context

We define interfaces of the inlang sdk in dedicated packages. The idea was to decrease the impact of breaking changes of interfaces on the ecosystem. However:

* plugins and lint rules import the sdk regardless of dedicated interface packages
* more complex codebase
* iteration speed slightly impacted see discussions like [https://github.com/opral/monorepo/pull/2700#issuecomment-2096782022](https://github.com/opral/monorepo/pull/2700#issuecomment-2096782022)

### Proposal

Remove the versioned interfaces and put them in the SDK. 

### Video 

[https://www.loom.com/share/ca91189f093940c38ae0f2927725b06c?sid=93b4ddf6-ce84-4581-91f3-97987224652d](https://www.loom.com/share/ca91189f093940c38ae0f2927725b06c?sid=93b4ddf6-ce84-4581-91f3-97987224652d)

**Comment by samuelstroschein** [comment]
cc @jldec (because the sdk is your baby), @loris.sigrist @martin.lysk1 (because you worked on the interfaces lately)

**Comment by LorisSigrist** [comment]
The reasoning behind moving the Data-Model into the SDK makes sense. <br><br>A concern I have is that this might cause large parts of the SDK to be bundled into the lint-rules / plugins. Everything but the types *should* be treeshaken but that's just one mistake away from silently breaking.

**Comment by jldec** [comment]
In cases where you just want the types, but *not* the whole sdk, you should still be able to import those from the sdk package without bundling the whole sdk, right?

**Comment by jldec** [comment]
regarding the package separation, I thought the main potential benefit of that would be separate releases with separate version numbers, but I don't believe we are making use of the version numbers to do auto-migration or to ship with support for multiple versions.

**Comment by jldec** [comment]
==> I agree with this proposal :)

**Comment by samuelstroschein** [comment]
implemented in sdk v2
