### ISSUE TITLE
query.messages.getByDefaultAlias not working in sherlock inline annotations

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#55]
### Context

* Open code file in a project with experimental.aliases set to true
* Previews for references to messages appear to be broken

![Screenshot 2024-05-10 at 10 43 21](https://github.com/opral/inlang-message-sdk/assets/849592/63b07988-7fb4-4d06-8ff1-4437a4c6d66a)
![Screenshot 2024-05-10 at 10 55 48](https://github.com/opral/inlang-message-sdk/assets/849592/9683d9c2-834a-4f95-93a2-c979590c1ed3)

### Proposal

* Fix aliases behavior for new persistence (don't translate id's to aliases)

See [MESDK-95](https://linear.app/opral/issue/MESDK-95/persist-aliases-and-remove-id-alias-mapping-on-load-from-internal)

**Comment by jldec** [comment]
@martin.lysk1 <br>I suspect that we broke the \`defaultAliasIndex\` in the changes to createMessagesQuery.ts in [https://github.com/opral/monorepo/pull/2709/](https://github.com/opral/monorepo/pull/2709/)<br><br>Would you mind taking a look please. <br><br>Sherlock users who open our monorepo/website project all see these alias errors when they open files like inlang/source-code/website/src/pages/index/Footer.tsx

**Comment by felixhaeberle** [comment]
Breaking already available APIs (even tho experimental) is something we should try to avoid. We have repeatedly communicated the API in chats&whatnot + using it ourselves – therefore would be nice to have this fixed, as Sherlock doesn't work otherwise (for us + potential early birds).

**Comment by martin-lysk** [comment]
I added a quick draft of it here.

@felix.haeberle I won't be able to run tests in sherlock on it right now - can you check it quickly. If its not working in the first shot i will setup the test env here. 

[https://github.com/opral/monorepo/pull/2895](https://github.com/opral/monorepo/pull/2895)

**Comment by jldec** [comment]
left some comments in the PR
