### ISSUE TITLE
`messages.getAll.subscribe` changed callback is not triggered when a message is removed

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-message-sdk#67]
### Context

When removing a message from, let's say, a `en.json` file the message-changed callback is not triggered. In paraglide's case this leads to a desync between the messages & the compiled output. 

This has caused some of the user reports about reactivity not working as expected

### Proposal

Trigger the callback

**Comment by jldec** [comment]
@martin.lysk1 could you take a look at this please?<br>(are we missing a test for removed messages?)

**Comment by martin-lysk** [comment]
Discussed this briefly with @LorisSigrist this morning. Definitely a blindspot in our coverage. I will look into it asap
