### ISSUE TITLE
Limit query.messages.getAll() events when multiple messages change

### ISSUE THREAD

**Issue by martin-lysk** [opral/inlang-message-sdk#72]
### Context

A sub sequential load of the messages after the initial load of the projects produces a signal per updated messages.

### Proposal

Batch message updates in loadViaPlugin and produce a signal at the very end of the load process.

**Comment by jldec** [comment]
@martin-lysk why is this change necessary? Is there a use case which will be improved, or issue fixed?

**Comment by martin-lysk** [comment]
compare thread in related [pr](https://github.com/opral/monorepo/pull/2821)
