### ISSUE TITLE
Load on demand and cache message bundles

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#83]
### Context

Maintaining all messages in memory limits scalabilty and slows down startup times. It would be better to load messages on demand and cache instead.

This would also align better with Lix lazy loading

### Proposal

The v2 persistence store should load on demand and cache message bundles.

**Comment by samuelstroschein** [comment]
What does "cache message bundles" mean?

**Comment by jldec** [comment]
Instead of keeping all message bundles in memory, we load them when they are needed, and cache the already-loaded ones - more like a queryable db, than a giant blob.<br><br>At the moment our default entity is a MessageBundle but we could do something similar at the translated Message level too, more like a relational DB with 2 tables.<br><br>This is is not blocking within current scale requirements, but it would be nice to mitigate the slowdown for bigger projects.
