### ISSUE TITLE
Use rename to write v2 store files atomically

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#86]
### Context

If the store process exits during a write, files should not be left in a partially written state.  

### Proposal

First write to a temp file and then rename.

This is related to [https://github.com/opral/inlang-message-sdk/issues/80](https://github.com/opral/inlang-message-sdk/issues/80), since we need to keep watching the file after rename.

**Comment by samuelstroschein** [comment]
> since we need to keep watching the file after rename.

In what scenario will a file be renamed? 

I assume that the file name will be the (human) id of the message. By definition, the human id will never change

**Comment by jldec** [comment]
[LIX-83](https://linear.app/opral/issue/LIX-83/fsrename-for-atomic-writes)
