### ISSUE TITLE
Better error message for invalid messages json file

### ISSUE THREAD

**Issue by thenbe** [opral/inlang-message-sdk#87]
## Current

These two scenarios result in the same error being logged ("missing messages") when running `npx vite dev`.

1. An invalid `pathPattern`:

```json
	"plugin.inlang.json": {
		"pathPattern": "./does/not/exist/{languageTag}.json"
	}
```

2. An invalid `en.json` file:

```json
{
	// this json file is not valid because it contains a comment
	"foo": "bar"
}
```

## Expected

The second scenario should provide a better error message to indicate the error is the result of invalid json.

## Repro

My setup was similar to this [example](https://github.com/LorisSigrist/paraglide-sveltekit-example)

**Comment by jldec** [comment]
@loris.sigrist <br>I can't repro this but perhaps I'm not doing it right. Moving the issue to paraglide<br><br>Since [https://github.com/opral/monorepo/pull/2681](https://github.com/opral/monorepo/pull/2681) JSON errors should be propagated<br>This is working for me with the example repo linked above, when i change en.json to have a error

```
$ p paraglide-js compile --project ./project.inlang/
ℹ [paraglide] Compiling inlang project at "./project.inlang/".                                                                                                          
Using existing cloned repo

 WARN  The project has errors:                                                                                                                                           


 ERROR  An error occured in loadMessages() caused by SyntaxError: Expected property name or '}' in JSON at position 3.                                                   

  at node_modules/.pnpm/@inlang+paraglide-js@1.9.1/node_modules/@inlang/paraglide-js/dist/index.js:9234:34

~/opral/paraglide-sveltekit-example$ 
```

<br>File not found errors are not considered errors a.t.m and the message file will be auto-created if missing, on first write. There is an issue to improve this.<br>[MESDK-99](https://linear.app/opral/issue/MESDK-99/plugins-should-error-if-the-source-language-messages-file-is-missing)

**Comment by jldec** [comment]
@thenbe could you please provide more specific steps to reproduce this (ideally link to a test repo on github) and your project.inlang/settings.json file.

**Comment by thenbe** [comment]
Here are the repro steps:

```bash
git clone https://github.com/LorisSigrist/paraglide-sveltekit-example.git
cd paraglide-sveltekit-example
pnpm install
echo '// i am a comment' >> messages/en.json
pnpm vite dev
```

And this is the full error message:

```
WARN  No messages found - Skipping compilation into ./src/lib/paraglide
```

**Comment by jldec** [comment]
@loris.sigrist i can confirm

* vite dev doesn't report the project error

```
$ echo '// i am a comment' >> messages/en.json
pnpm vite dev
Using existing cloned repo

 WARN  No messages found - Skipping compilation into ./src/lib/paraglide                                                                                 


  VITE v5.2.12  ready in 3182 ms
```

* paraglide-js compile does

```
$ pnpm paraglide-js compile --project project.inlang/
ℹ [paraglide] Compiling inlang project at "project.inlang/".                                                                                            
Using existing cloned repo

 WARN  The project has errors:                                                                                                                           


 ERROR  An error occured in loadMessages() caused by SyntaxError: Expected property name or '}' in JSON at position 3.                                   

  at node_modules/.pnpm/@inlang+paraglide-js@1.9.1/node_modules/@inlang/paraglide-js/dist/index.js:9234:34

$
```
