### ISSUE TITLE
extract `parsePattern` & `addVariantToMessage` into `@inlang/sdk`

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-sdk#88]
https://github.com/opral/monorepo/blob/e29b3361db6994a489beaac3acd116c9ce609877/inlang/source-code/plugins/next-intl/src/plugin.ts#L154-L234

Hey @jldec ,

I stumbled over this code, which seems to belong in the SDK; what do you think? 
Similar implementations are likely to be found in the JSON & i18next plugins.

How do we treat message parsing/variant creation in the new SDK v2 implementations?

In my understanding, multiple libraries may have different syntaxes to support, so the plugin should be used only as a bridge to execute functions with some library-specific arguments. Still, the functions should be within the SDK – I guess. 

This raises the question: How does importer/exporter change the plugin landscape and functions?

Sorry for raising that many questions, but hopefully, you can clarify a bit🙏

**Comment by felixhaeberle** [comment]
cc @samuelstroschein @martin-lysk who maybe also have an idea how this can involve.

**Comment by samuelstroschein** [comment]
Are you asking if parsing third party message syntaxes belongs to the inlang SDK? <br><br>If so, the answer is no. Plugins are responsible for parsing and serializing third party message syntaxes. The SDK concerns itself with our own format.

**Comment by samuelstroschein** [comment]
ah. utlity functions like `createMessage` etc don't exist atm because we did not reach a consensus how those functions should work (cc @loris.sigrist). the discussion was concluded with "let everyone hand roll for now and then see what's next". 

---

> Overall, the communication and responsibility of plugins is a mess.

This seems to be an unrelated issue? Discuss somewhere else?

> 1. Some do only provide message loading/saving.
> 2. Some do only provide matching functionality for Sherlock.

The website (cc @nils.jacobsen) just misses a "this plugin defines xyz" section and explainer what x,y, or z do on the product page. I did a sketch a while ago but can't find it anymore.

**Comment by jldec** [comment]
relevant discussion (decision not to introduce a new pattern parser for now) in [https://github.com/opral/monorepo/pull/2795#issuecomment-2116397305](https://github.com/opral/monorepo/pull/2795#issuecomment-2116397305)<br><br>fyi - I also asked @nils.jacobsen to hold off on extracting sdk helpers for the new v2 MessageBundle format, until we're further along with the v2 sdk api. <br><br>NOTE: There are already 2 very basic [helpers](https://github.com/opral/monorepo/blob/main/inlang/source-code/sdk/src/v2/helper.ts) to create v2 MessageBundle and Message types which we can use for testing. They assume simple strings without variants like v1.

**Comment by felixhaeberle** [comment]
@opral/inlang-plugins Can you create a follow-up task to #2795 updating the plugins when ready?

**Comment by samuelstroschein** [comment]
@felix.haeberle please don't use github. people don't get notifications on linear.

**Comment by felixhaeberle** [comment]
@samuelstroschein We do not have a plugin team in inlang AFAIK.

**Comment by NilsJacobsen** [comment]
There is also nobody responsible for plugins right now. I would propose that you (@felix.haeberle) do it because you will add more plugins in the next days.

**Comment by felixhaeberle** [comment]
@nils.jacobsen Alright, lets do it that way 👍
