### ISSUE TITLE
IDs to reference Messages and Variants

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#92]
### Context

Lint reports need to reference Messages (in a MessageBundle) and Variants (in a Message).<br>This means that we need unique identifiers for Messages and Variants in our apis.

* Using array indices in the AST is not good enough (breaks when entities are added)
* Using a combination of the Message Bundle id, and the locale, would be an option for Messages 
* Similarly, variants for a specific Message could be identified by their select matches
* Using something like uuids is simpler but requires additional memory

Do the ids need to be persisted?

* yes if references (from lint reports) need be stable across sessions.

See [INLMC-85](https://linear.app/opral/issue/INLMC-85/how-do-we-deal-with-lints-in-variants)

### Proposal

* instead of globally unique ids (uuid) I would suggest shorter keys, only unique within a project.

cc: @samuel.stroschein @martin.lysk1

**Comment by jldec** [comment]
added to persistence project and bumped in priority

**Comment by samuelstroschein** [comment]
i agree that everything needs ids: message bundles (human ids), messages, variants

> only unique within a project.

what algorithm to you propose? uuid might be longer but uniqueness in a distributed system should be OK. Plus, good libraries exist.

**Comment by jldec** [comment]
good point - id's not only have to be unique within one instance of the project, but across all project instances that create new ids and then commit them. <br><br>one option would be random 8 or 10 character base-36 strings - 36\*\*8 gives you >10\*\*12
