### ISSUE TITLE
How do we deal with empty entries (messages and variants)

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-sdk#93]
I'm not a super pro of the new slot system, but here is a short draft about what empty entries mean for different kind of situations.<br><br>@jldec @martin.lysk1 <br>Short prep for tomorrow discussion.

<br>-> [https://www.loom.com/share/5b781f774c3545b99cbffbef244ecbbc](https://www.loom.com/share/5b781f774c3545b99cbffbef244ecbbc)<br>-> [https://app.excalidraw.com/s/1RmnkzJA3Ph/74di1HkQUo2](https://app.excalidraw.com/s/1RmnkzJA3Ph/74di1HkQUo2)

**Comment by martin-lysk** [comment]
Thanks @nils.jacobsen  will have a look!

One note in advanced: the slot system has nothing to do with empty entries for messages and variants ;-)

**Comment by jldec** [comment]
\# **topics**

1.  When Messages for a locale are not present in the data they always trigger missing-translation lint rule. After editing and saving a translation, can you delete it entirely. Why is this not the same as detecting an empty string? Empty can mean fallback. It would be nice not to re-trigger the lint just for that Message (issue exists)
2. When is a Message saved? Ideally there is no explicit save action.
3. Regarding variants, declarations, and matchers: How do users avoid saving messaages with missing elements and other inconsistencies. This is an important topic for the editor component

**Comment by NilsJacobsen** [comment]
The outcome from the meeting on Tuesday:

* Every state should be displayable in the ui (bad state can be hacked or a result from merging)
* Merge conflicts can be shown in an other ui component (gitfloat, right or left)
* When the message is completely broken by a conflict show error state
* Empty variants, messages get linted

**Comment by samuelstroschein** [comment]
Closing as stale.
